### ISSUE TITLE
This is what I get when I try to update past 3.8.7

### ISSUE THREAD

**Issue by oakmaster** [nwoolls/MultiMiner#209]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at MultiMiner.UX.ViewModels.ApplicationViewModel.DownloadRequiredMiners() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 2229
   at MultiMiner.UX.ViewModels.ApplicationViewModel.StartMiningLocally() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 2051
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18063 built by: FX45RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
    Assembly Version: 4.0.1.357
    Win32 Version: 4.0.1.357
    CodeBase: file[Suspicious link removed]
----------------------------------------

Its driving me crazy I haven't been able to update MM I don't get why no problems with 3.8.7 and under as soon as I go above this happens 
Thank You for your great work and what ever advice you could give me on this issue

**Comment by nwoolls** [comment]
You are running 4.0.0, please download and install 4.0.1 from the releases page:

https://github.com/nwoolls/MultiMiner/releases

And re-post the error message if it persists. Your error does not line up with the current code-base.

**Comment by nwoolls** [comment]
Looks to me like your XgminerConfiguration.xml contains AlgorithmMiner settings for miners that are no longer found in Miners\. Did you extract the zip to a new location or extract the files over your previous installation?

Try extracting 4.0.1 over your 3.8.7 install or, alternatively, copying the Miners folder from your 3.8.7 install over to 4.0.1. Please let me know if / how that works.

**Comment by nwoolls** [comment]
@oakmaster can you please try this build to see if it resolves the error for you?

https://www.dropbox.com/s/o1x1n7qd9ctfhgb/MultiMiner-4.0.1.zip?dl=0

**Comment by oakmaster** [comment]
that worked thanks I was going nuts everytime I tried to install a update I just had to go into gpu settings change the kernel for x11 and a few of the othe backend miners I installed but thanks a lot love ur work

**Comment by nwoolls** [comment]
Fixed in 31aca8a800eebbef83187d4cea0e8152c0096692
