### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Robeardley** [nwoolls/MultiMiner#211]
It was all going so well then I had the dreaded Unhanded Exception has occurred in your application. 

Firstly is there an easy fix.

second is it gonna keep happening ...

and if the answer to that is yes will you talk me through installing VCP into Linux and I'll spend a couple of days syncing wallets in that and start again.

Heres the error message and many thanks in advance

Very best wishes
Rob

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sequence contains no matching element
  at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
  at MultiMiner.Engine.MiningEngine.CreateDeviceConfigurationForProfitableCoins(List`1 allProfitableCoins, List`1 sha256ProfitableCoins, List`1 scryptProfitableCoins) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Engine\MiningEngine.cs:line 542
  at MultiMiner.Engine.MiningEngine.CreateAutomaticDeviceConfiguration(IEnumerable`1 orderedCoinInformation) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Engine\MiningEngine.cs:line 516
  at MultiMiner.Engine.MiningEngine.ApplyMiningStrategy(List`1 coinInformation) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Engine\MiningEngine.cs:line 401
  at MultiMiner.Engine.MiningEngine.StartMining(Engine engineConfiguration, List`1 devices, List`1 coinInformation, Int32 donationPercent) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Engine\MiningEngine.cs:line 197
  at MultiMiner.UX.ViewModels.ApplicationViewModel.StartMiningLocally() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 2055
  at MultiMiner.UX.ViewModels.ApplicationViewModel.StartMining() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 1867
  at MultiMiner.Win.Forms.MinerForm.HandleStartButtonClicked() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 1222
  at MultiMiner.Win.Forms.MinerForm.startButton_Click(Object sender, EventArgs e) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 1214
  at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
  at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
  at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
  at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
  at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
  at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
  at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
  at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
  at System.Windows.Forms.Control.WndProc(Message& m)
  at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
  at System.Windows.Forms.ToolStrip.WndProc(Message& m)
  at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
  at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
  at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
   Assembly Version: 4.0.0.0
   Win32 Version: 4.0.30319.18063 built by: FX45RTMGDR
   CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
   Assembly Version: 4.0.2.359
   Win32 Version: 4.0.2.359
   CodeBase: file:///C:/Users/Rob/Desktop/MultiMiner-4.0.2/MultiMiner.Win.exe
----------------------------------------

**Comment by nwoolls** [comment]
Please try the following release and report back if it fixes the problem:

https://www.dropbox.com/s/lnsee7m6t7hysc3/MultiMiner-4.0.2.zip?dl=0

**Comment by Robeardley** [comment]
Good morning,

apologies for not getting on this immediately yesterday.

So far this morning I have installed the new version and set it mining.

Stopped it.  Shut it down.  Re-started it and started ming again,  all without incident or error.

I then shut down the PC completely and had to wait for MS Updates in the process,  re-started and set Multiminer to work once again,  all without incident or error.

It’s mining away as i type.  

I will probably shut down and re-start again over the weekend just to bolster my confidence but so far it looks solid.

Many thanks

Rob

**Comment by nwoolls** [comment]
Fixed in 202131aa2cf7b58746124aa0b64b987b360779f1
