### ISSUE TITLE
Invalid URI: The Hostname could not be parsed

### ISSUE THREAD

**Issue by amyehya** [nwoolls/MultiMiner#236]
Hi,

After a day with Multiminer working great, it stopped running and then when I tried to run it I got this error. 

Unhandled exception has occurred in your application. 
Invalid URI: The hostname could not be parsed.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder..ctor(String uri)
   at MultiMiner.Xgminer.Miner.Launch(String reason) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Xgminer\Miner.cs:line 238
   at MultiMiner.Engine.MiningEngine.LaunchMinerProcess(Miner minerConfiguration, String reason) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Engine\MiningEngine.cs:line 861
   at MultiMiner.Engine.MiningEngine.LaunchMiners(Int32& apiPort, String coinSymbol, DeviceKind deviceKind, Boolean terminateProcess) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Engine\MiningEngine.cs:line 818
   at MultiMiner.Engine.MiningEngine.StartMining() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Engine\MiningEngine.cs:line 740
   at MultiMiner.Engine.MiningEngine.StartMining(Engine engineConfiguration, List`1 devices, List`1 coinInformation, Int32 donationPercent) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Engine\MiningEngine.cs:line 200
   at MultiMiner.UX.ViewModels.ApplicationViewModel.StartMiningLocally() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 2055
   at MultiMiner.UX.ViewModels.ApplicationViewModel.StartMining() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 1867
   at MultiMiner.Win.Forms.MinerForm.HandleStartButtonClicked() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 1222
   at MultiMiner.Win.Forms.MinerForm.startButton_Click(Object sender, EventArgs e) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 1214
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

What can I do here to resolve this.

**Comment by nwoolls** [comment]
Sounds like you have an invalid value under the Host field for one of your pools. Click the Pools button and check each entry. If all else fails you can nuke the ```CoinConfigurations.xml``` file in ```%appdata%\MultiMiner%.

**Comment by shanekarstens** [comment]
I just went trough this exact problem. I had to delete everything and start over for it to clear that error.
