### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Brendanms900** [nwoolls/MultiMiner#252]
I cannot seem to find anything about this exception

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MultiMiner.UX.ViewModels.ApplicationViewModel.AddMissingDeviceConfigurations() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 743
   at MultiMiner.UX.ViewModels.ApplicationViewModel.ConfigurePoolsLocally() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 556
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

MultiMiner.Win
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.Win.exe

MultiMiner.UX
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.UX.DLL

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

MultiMiner.Engine
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.Engine.DLL

MultiMiner.Utility
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.Utility.DLL

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

MultiMiner.CoinApi
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.CoinApi.DLL

MultiMiner.Xgminer.Api
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.Xgminer.Api.DLL

MultiMiner.Xgminer
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.Xgminer.DLL

MultiMiner.MobileMiner
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.MobileMiner.DLL

MultiMiner.Discovery
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.Discovery.DLL

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

MultiMiner.Remoting
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.Remoting.DLL

MultiMiner.CoinWarz
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.CoinWarz.DLL

MultiMiner.CoinChoose
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.CoinChoose.DLL

MultiMiner.WhatMine
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.WhatMine.DLL

MultiMiner.WhatToMine
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.WhatToMine.DLL

Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/Newtonsoft.Json.DLL

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

MultiMiner.MultipoolApi
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.MultipoolApi.DLL

MultiMiner.NiceHash
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.NiceHash.DLL

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

MultiMiner.ExchangeApi
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.ExchangeApi.DLL

Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll

System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll

Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll

MultiMiner.Services
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.Services.DLL

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

MultiMiner.MobileMiner.Embed
    Assembly Version: 4.0.4.362
    Win32 Version: 4.0.4.362
##     CodeBase: file:///C:/Users/Brendan/Downloads/MultiMiner.app/Contents/Resources/MultiMiner.MobileMiner.Embed.DLL

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Netzarim** [comment]
I just started getting this same error...

**Comment by madhan5** [comment]
I got the same error how to fix it?

**Comment by nwoolls** [comment]
Delete the settings for MultiMiner on your PC and reconfigure it. Unfortunately I do not use or develop MultiMiner anymore. So you will likely only get responses from other users.

**Comment by nwoolls** [comment]
Settings are in `%appdata%\MultiMiner` afaik.

**Comment by nwoolls** [comment]
@Brendanms900 I cannot seem to reproduce this. If this issue is still occurring, can you send the contents of your `%appdata\MultiMiner%` folder to me via email - nwoolls at gmail.com.

**Comment by nwoolls** [comment]
Closing due to no response. If this problem persists, please reopen the issue.
