### ISSUE TITLE
Multiminer 4.0.4 throws .net error when launched

### ISSUE THREAD

**Issue by gn3t1c** [nwoolls/MultiMiner#279]
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MultiMiner.NiceHash.ApiContext.GetMultipoolInformation(String userAgent) in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.NiceHash\ApiContext.cs:line 18
   at MultiMiner.UX.ViewModels.ApplicationViewModel.GetNiceHashInformation() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 332
   at MultiMiner.UX.ViewModels.ApplicationViewModel.RefreshNiceHashStats() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 288
   at MultiMiner.UX.ViewModels.ApplicationViewModel.RefreshCoinStats() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 2492
   at MultiMiner.Win.Forms.MinerForm.SetupApplication() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2143
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.Win.exe
----------------------------------------
MultiMiner.UX
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.UX.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
MultiMiner.Engine
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.Engine.DLL
----------------------------------------
MultiMiner.Utility
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.Utility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
MultiMiner.CoinApi
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.CoinApi.DLL
----------------------------------------
MultiMiner.Xgminer.Api
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.Xgminer.Api.DLL
----------------------------------------
MultiMiner.Xgminer
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.Xgminer.DLL
----------------------------------------
MultiMiner.MobileMiner
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.MobileMiner.DLL
----------------------------------------
MultiMiner.Discovery
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.Discovery.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.CoinWarz
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.CoinWarz.DLL
----------------------------------------
MultiMiner.CoinChoose
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.CoinChoose.DLL
----------------------------------------
MultiMiner.WhatMine
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.WhatMine.DLL
----------------------------------------
MultiMiner.WhatToMine
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.WhatToMine.DLL
----------------------------------------
MultiMiner.Remoting
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.Remoting.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.MultipoolApi
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.MultipoolApi.DLL
----------------------------------------
MultiMiner.NiceHash
    Assembly Version: 4.1.0.363
    Win32 Version: 4.1.0.363
    CodeBase: file:///C:/Users/geigerg/AppData/Local/MultiMiner/MultiMiner.NiceHash.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by nwoolls** [comment]
@gn3t1c I cannot seem to reproduce this. If this issue is still occurring, can you send the contents of your `%appdata\MultiMiner%` folder to me via email - nwoolls at gmail.com.

**Comment by nwoolls** [comment]
Closing due to no response. If this problem persists, please reopen the issue.
