### ISSUE TITLE
KeyNotFoundException error refreshing Network Device stats

### ISSUE THREAD

**Issue by tutorialevideo** [nwoolls/MultiMiner#336]
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MultiMiner.Xgminer.Api.Parsers.NetworkCoinInformationParser.ParseTextForCoinNetworkInformation(String text, NetworkCoinInformation coinInformation) in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Xgminer.Api\Parsers\NetworkCoinInformationParser.cs:line 24
   at MultiMiner.Xgminer.Api.ApiContext.GetCoinInformation() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Xgminer.Api\ApiContext.cs:line 78
   at MultiMiner.UX.ViewModels.ApplicationViewModel.GetNetworkDifficultyFromMiner(ApiContext apiContext) in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 4065
   at MultiMiner.UX.ViewModels.ApplicationViewModel.CheckAndSetNetworkDifficulty(String ipAddress, Int32 port, String poolUri) in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 4058
   at MultiMiner.UX.ViewModels.ApplicationViewModel.<>c__DisplayClass71.<RefreshNetworkDeviceStatsAsync>b__70() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 1165


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.Win.exe
----------------------------------------
MultiMiner.UX
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.UX.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
MultiMiner.Engine
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.Engine.DLL
----------------------------------------
MultiMiner.Utility
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.Utility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
MultiMiner.CoinApi
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.CoinApi.DLL
----------------------------------------
MultiMiner.Xgminer.Api
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.Xgminer.Api.DLL
----------------------------------------
MultiMiner.Xgminer
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.Xgminer.DLL
----------------------------------------
MultiMiner.MobileMiner
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.MobileMiner.DLL
----------------------------------------
MultiMiner.Discovery
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.Discovery.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Remoting
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.Remoting.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.CoinWarz
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.CoinWarz.DLL
----------------------------------------
MultiMiner.WhatToMine
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.WhatToMine.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
MultiMiner.MultipoolApi
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.MultipoolApi.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Services
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.Services.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Blockchain
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.Blockchain.DLL
----------------------------------------
MultiMiner.ExchangeApi
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.ExchangeApi.DLL
----------------------------------------
MultiMiner.Stats
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.Stats.DLL
----------------------------------------
MultiMiner.Xgminer.Discovery
    Assembly Version: 4.2.2.376
    Win32 Version: 4.2.2.376
    CodeBase: file:///C:/Users/remote/AppData/Local/MultiMiner/MultiMiner.Xgminer.Discovery.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by nwoolls** [comment]
See also the docs for the `COIN` API verb:

* https://github.com/ckolivas/cgminer/blob/master/API-README

```
 coin          COIN           Coin mining information:
                              Hash Method=sha256/scrypt,
                              Current Block Time=N.N, <- 0 means none
                              Current Block Hash=XXXX..., <- blank if none
                              LP=true/false, <- LP is in use on at least 1 pool
                              Network Difficulty=NN.NN|
```

**Comment by nwoolls** [comment]
A work around for this will be included in the next update but I'd still love to know the offending miner.
