### ISSUE TITLE
No copy of BFGMiner was detected loop error

### ISSUE THREAD

**Issue by erixjokey** [nwoolls/MultiMiner#397]
After installing running MultiMiner 4.3.0 (tried older versions too) I get the notification _"No Copy of BFGMiner was detected. Would you like to download and install BFGMiner now?_" After clicking yes, _"downloading window"_ pops up and disappears and the same Miner Not Found windows appears. 
I tried to copy BFGMiner 5.5 folder to _Miners/BFGMiner_ but got a Microsoft .NET Framework error (I installed all .net versions) . After that tried to install it manually through MinGW but it didn't change anything.

```
Microsoft .NET Framework
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at MultiMiner.Services.DevicesService.GetDevices(String executablePath) in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Services\DevicesService.cs:line 35
   at MultiMiner.UX.ViewModels.ApplicationViewModel.ScanHardwareLocally() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 1934
   at MultiMiner.Win.Forms.MinerForm.ScanHardwareLocally() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2864
   at MultiMiner.Win.Forms.MinerForm.SetupApplication() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2221
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.Win.exe
----------------------------------------
MultiMiner.UX
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.UX.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
MultiMiner.Engine
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.Engine.DLL
----------------------------------------
MultiMiner.Utility
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.Utility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
MultiMiner.CoinApi
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.CoinApi.DLL
----------------------------------------
MultiMiner.Xgminer.Api
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.Xgminer.Api.DLL
----------------------------------------
MultiMiner.Xgminer
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.Xgminer.DLL
----------------------------------------
MultiMiner.MobileMiner
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.MobileMiner.DLL
----------------------------------------
MultiMiner.Discovery
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.Discovery.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Remoting
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.Remoting.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.CoinWarz
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.CoinWarz.DLL
----------------------------------------
MultiMiner.WhatToMine
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.WhatToMine.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Services
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.Services.DLL
----------------------------------------
MultiMiner.Blockchain
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.Blockchain.DLL
----------------------------------------
MultiMiner.ExchangeApi
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///C:/Users/IzoBlanc/Desktop/New%20folder/MultiMiner-4.3.0/MultiMiner.ExchangeApi.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by ArranMoney** [comment]
I'm having the same issue and I can't use it at all. Does anyone know a fix for this?

**Comment by PedroxTheBest99** [comment]
Same here
I'm using Windows 10 2004, so it SHOULD work

**Comment by Batchwise** [comment]
Seeing this one as well - should we be installing the miner separately?  If so, before of after multiminer app?

**Comment by ImMX96** [comment]
I am having the same issue, before I found this miner I already had BFGminer on my computer but not installed. There was not a Miners folder anywhere, and had to create one and unzipped the file into that folder. It did not work, and this error is still prominent.
