### ISSUE TITLE
Null parameter 'uriString' when installing BFGMiner

### ISSUE THREAD

**Issue by TheFizzWare** [nwoolls/MultiMiner#404]
After seeing the "No copy of BFGMiner was detected. Would you like to download and install BFGMiner now?" prompt and clicking "yes", I get the following unhandled null argument exception:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at MultiMiner.UX.ViewModels.ApplicationViewModel.InstallBackendMinerLocally(MinerDescriptor miner) in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 2219
   at MultiMiner.Win.Forms.MinerForm.ShowNotInstalledMinerWarning() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2580
   at MultiMiner.Win.Forms.MinerForm.ScanHardwareLocally() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2875
   at MultiMiner.Win.Forms.MinerForm.SetupApplication() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2221
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.Win.exe
----------------------------------------
MultiMiner.UX
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.UX.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
MultiMiner.Engine
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.Engine.DLL
----------------------------------------
MultiMiner.Utility
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.Utility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
MultiMiner.CoinApi
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.CoinApi.DLL
----------------------------------------
MultiMiner.Xgminer.Api
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.Xgminer.Api.DLL
----------------------------------------
MultiMiner.Xgminer
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.Xgminer.DLL
----------------------------------------
MultiMiner.MobileMiner
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.MobileMiner.DLL
----------------------------------------
MultiMiner.Discovery
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.Discovery.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Remoting
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.Remoting.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.CoinWarz
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.CoinWarz.DLL
----------------------------------------
MultiMiner.WhatToMine
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.WhatToMine.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Services
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.Services.DLL
----------------------------------------
MultiMiner.Blockchain
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.Blockchain.DLL
----------------------------------------
MultiMiner.ExchangeApi
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/FizzWare/AppData/Local/MultiMiner/MultiMiner.ExchangeApi.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

This is on a new installation of MultiMiner on Windows 10.

**Comment by forReason** [comment]
same here. how to install it manually?

**Comment by TheFizzWare** [comment]
> 
> 
> same here. how to install it manually?

I'd like to know as well - it would be very helpful if someone with a working MultiMiner w/ BFGMiner installation could post their file tree structure to help us identify the way BFGMiner is installed onto the system to assist us in doing so manually.

**Comment by felendaren** [comment]
Guys complete to errors dowload to links https://mega.nz/file/5D4WDIRC#iv6lM6p_TrbX1yjb3WBa38YYUT45WWH88pheFj0WWVE

**Comment by felendaren** [comment]
Dowloads https://mega.nz/file/5D4WDIRC#iv6lM6p_TrbX1yjb3WBa38YYUT45WWH88pheFj0WWVE

**Comment by ghost** [comment]
I have this same issue, any fix yet?

**Comment by DerekZiemba** [comment]
@felendaren You linked to the 32bit version. 

## Workaround for 'Null parameter 'uriString' when installing BFGMiner'
1. Download correct BFGMiner (64bit or 32bit) from http://bfgminer.org/
2. Go to wherever MultiMiner is installed 
    - create a new folder called `Miners` and in that folder create another new folder called `BFGMiner`
    - The path should be  `.\MultiMiner\Miners\BFGMiner\`
3. Extract `~\Downloads\bfgminer-5.5.0-win64.zip` to  `~\Downloads\bfgminer-5.5.0-win64`
    - Copy or Cut the contents inside `~\Downloads\bfgminer-5.5.0-win64\**` 
    - Paste them to `.\MultiMiner\Miners\BFGMiner\**`
    - Can now delete `~\Downloads\bfgminer-5.5.0-win64.zip` & `~\Downloads\bfgminer-5.5.0-win64`
5. Now launch `.\MultiMiner\MultiMiner.Win.exe`

**Comment by Squishy420** [comment]
Use 32 version of BFGMiner and install manually. 

> @felendaren You linked to the 32bit version.
> 
> ## Workaround for 'Null parameter 'uriString' when installing BFGMiner'
> 1. Download correct BFGMiner (64bit or 32bit) from http://bfgminer.org/
> 2. Go to wherever MultiMiner is installed
>    
>    * create a new folder called `Miners` and in that folder create another new folder called `BFGMiner`
>    * The path should be  `.\MultiMiner\Miners\BFGMiner\`
> 3. Extract `~\Downloads\bfgminer-5.5.0-win64.zip` to  `~\Downloads\bfgminer-5.5.0-win64`
>    
>    * Copy or Cut the contents inside `~\Downloads\bfgminer-5.5.0-win64\**`
>    * Paste them to `.\MultiMiner\Miners\BFGMiner\**`
>    * Can now delete `~\Downloads\bfgminer-5.5.0-win64.zip` & `~\Downloads\bfgminer-5.5.0-win64`
> 4. Now launch `.\MultiMiner\MultiMiner.Win.exe`

**Comment by CodeChief** [comment]
If it's the cost of hosting which in the problem, how about using the new Azure Static Web App, which I understand allows free hosting (or at least much cheaper in case there are hidden fees) including SSL which we need to be certain only the correct miner update is downloaded. Only restriction I can see is you must publish from a GitHub repository. Sounds perfect, in case hosting is your problem?

https://azure.microsoft.com/en-us/services/app-service/static/

**Comment by AeShevch** [comment]
> Use 32 version of BFGMiner and install manually.
> 
> > @felendaren You linked to the 32bit version.
> > ## Workaround for 'Null parameter 'uriString' when installing BFGMiner'
> > 
> > 1. Download correct BFGMiner (64bit or 32bit) from http://bfgminer.org/
> > 2. Go to wherever MultiMiner is installed
> >    
> >    * create a new folder called `Miners` and in that folder create another new folder called `BFGMiner`
> >    * The path should be  `.\MultiMiner\Miners\BFGMiner\`
> > 3. Extract `~\Downloads\bfgminer-5.5.0-win64.zip` to  `~\Downloads\bfgminer-5.5.0-win64`
> >    
> >    * Copy or Cut the contents inside `~\Downloads\bfgminer-5.5.0-win64\**`
> >    * Paste them to `.\MultiMiner\Miners\BFGMiner\**`
> >    * Can now delete `~\Downloads\bfgminer-5.5.0-win64.zip` & `~\Downloads\bfgminer-5.5.0-win64`
> > 4. Now launch `.\MultiMiner\MultiMiner.Win.exe`

How can i do it on mac?

**Comment by Cyldavor** [comment]
The website has been taken down and you can no longer install the file off of github, does anyone have a recommendation for where I can get a reliable download of the most recent version of the file?
