### ISSUE TITLE
BFG miner unhandled exception

### ISSUE THREAD

**Issue by EducatedMF** [nwoolls/MultiMiner#409]
Can't download BFG miner, this is what I get:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at MultiMiner.UX.ViewModels.ApplicationViewModel.InstallBackendMinerLocally(MinerDescriptor miner) in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 2219
   at MultiMiner.Win.Forms.MinerForm.ShowNotInstalledMinerWarning() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2580
   at MultiMiner.Win.Forms.MinerForm.ScanHardwareLocally() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2875
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.Win.exe
----------------------------------------
MultiMiner.UX
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.UX.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
MultiMiner.Engine
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.Engine.DLL
----------------------------------------
MultiMiner.Utility
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/../AppData/Local/MultiMiner/MultiMiner.Utility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
MultiMiner.CoinApi
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.CoinApi.DLL
----------------------------------------
MultiMiner.Xgminer.Api
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.Xgminer.Api.DLL
----------------------------------------
MultiMiner.Xgminer
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.Xgminer.DLL
----------------------------------------
MultiMiner.MobileMiner
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.MobileMiner.DLL
----------------------------------------
MultiMiner.Discovery
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.Discovery.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Remoting
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.Remoting.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.CoinWarz
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.CoinWarz.DLL
----------------------------------------
MultiMiner.WhatToMine
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.WhatToMine.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Services
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.Services.DLL
----------------------------------------
MultiMiner.Blockchain
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.Blockchain.DLL
----------------------------------------
MultiMiner.ExchangeApi
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/../AppData/Local/MultiMiner/MultiMiner.ExchangeApi.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Xgminer.Discovery
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/.../AppData/Local/MultiMiner/MultiMiner.Xgminer.Discovery.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by CryptikWizard** [comment]
https://github.com/nwoolls/MultiMiner/issues/404#issuecomment-769933167
This work around does work. I just did it and Multiminer is working now.Also i went and grabbed the BFGminer.org zip. I'm not sure if it was different in any way, you may just want to save some time and just go with what worked.  Make sure to use the x86(32bit)zip, even though the directions say 64bit. I had to do it twice, second time was the x86.

Squishy420 quote is where you want to look.  he has the edit of 64bit    good luck!!

**Comment by Zorro962** [comment]
I get an error when Multiminer tries to download and install BFGminer.
![BFGminer error](https://user-images.githubusercontent.com/63992470/108615109-8662a100-73ce-11eb-8d68-faf9ac40dfa2.PNG)

**Comment by PLARulez** [comment]
> [#404 (comment)](https://github.com/nwoolls/MultiMiner/issues/404#issuecomment-769933167)
> This work around does work. I just did it and Multiminer is working now.Also i went and grabbed the BFGminer.org zip. I'm not sure if it was different in any way, you may just want to save some time and just go with what worked. Make sure to use the x86(32bit)zip, even though the directions say 64bit. I had to do it twice, second time was the x86.
> 
> Squishy420 quote is where you want to look. he has the edit of 64bit good luck!!

This finally works, I tinkered around for hours until using the 32bit just worked, mining now
