### ISSUE TITLE
Cannot install BFG Miner

### ISSUE THREAD

**Issue by windowcenter** [nwoolls/MultiMiner#410]
I get message No copy of BFGMiner was detected.  Would you like to install it now?  I choose "yes".

Then I get a Microsoft .Net Framework error (see attached file).  I click Continue, which takes me to the MultiMiner home page.  But there is a Notification saying Error checking for backend miner availability (404).
[error.pdf](https://github.com/nwoolls/MultiMiner/files/5948024/error.pdf)

**Comment by OGStryker** [comment]
Getting the same error when it tries to download BFGMiner after install. Full error details:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at MultiMiner.UX.ViewModels.ApplicationViewModel.InstallBackendMinerLocally(MinerDescriptor miner) in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:line 2219
   at MultiMiner.Win.Forms.MinerForm.ShowNotInstalledMinerWarning() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2580
   at MultiMiner.Win.Forms.MinerForm.ScanHardwareLocally() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2875
   at MultiMiner.Win.Forms.MinerForm.SetupApplication() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:line 2221
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.Win.exe
----------------------------------------
MultiMiner.UX
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.UX.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
MultiMiner.Engine
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.Engine.DLL
----------------------------------------
MultiMiner.Utility
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.Utility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
MultiMiner.CoinApi
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.CoinApi.DLL
----------------------------------------
MultiMiner.Xgminer.Api
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.Xgminer.Api.DLL
----------------------------------------
MultiMiner.Xgminer
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.Xgminer.DLL
----------------------------------------
MultiMiner.MobileMiner
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.MobileMiner.DLL
----------------------------------------
MultiMiner.Discovery
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.Discovery.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Remoting
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.Remoting.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.CoinWarz
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.CoinWarz.DLL
----------------------------------------
MultiMiner.WhatToMine
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.WhatToMine.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
MultiMiner.Services
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.Services.DLL
----------------------------------------
MultiMiner.Blockchain
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.Blockchain.DLL
----------------------------------------
MultiMiner.ExchangeApi
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/corey/AppData/Local/MultiMiner/MultiMiner.ExchangeApi.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by OGStryker** [comment]
I was able to successfully perform a manual install of 32-bit BFGMiner as suggested in another thread.

**Comment by shakinbakin** [comment]
I'm having this same JIT error but am unable to fix it even with a manual install of BFGMiner. I no longer get the BFGMiner error, just the JIT error now.

**Comment by ShefardPT** [comment]
> I was able to successfully perform a manual install of 32-bit BFGMiner as suggested in another thread.

Link plz?

**Comment by OGStryker** [comment]
> > I was able to successfully perform a manual install of 32-bit BFGMiner as suggested in another thread.
> 
> Link plz?

https://github.com/nwoolls/MultiMiner/issues/404#issuecomment-769933167

**Comment by haveitall1** [comment]
Same issue.  Unhandled exception.

If I try to continue anyway, it tries to install in C/whatever  and fails...

**Comment by tunisiano187** [comment]
Same problem for me.
But in the logs, it's talking about your windows local profile @nwoolls , maybe it can help you find the problem ?
Even by adding the bgfminer locally, i still receive the error

**Comment by DuReaLDuCK** [comment]
404 Web Site not found.
**Custom domain has not been configured inside Azure**. See https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-tutorial-custom-domain how to map an existing domain
Client cache is still pointing the domain to old IP address. Clear the cache by running the command ipconfig/flushdns.
https://blogs.msdn.microsoft.com/appserviceteam/2017/08/08/faq-app-service-domain-preview-and-custom-domains App Service Domain FAQ  for more questions.

Looks like Azure configuration problem.
