### ISSUE TITLE
MultiMiner v4.3.1 Microsoft .NET Framework and error 404

### ISSUE THREAD

**Issue by lkompowski** [nwoolls/MultiMiner#436]
Hi, 

I've a problem installing MultiMiner v4.3.1.exe. I'm running on Windows 10 Home, x64. Windows Defender was closed as well as Windows protections againts viruses and threats. Firstly i tried to install MultiMiner. I saw the screen

![1](https://user-images.githubusercontent.com/92303654/136780803-3b933a50-353c-4918-8980-fb059f12f542.jpg)
and clicked yes. A while after this screen appered.
![2](https://user-images.githubusercontent.com/92303654/136780968-c1e42bdf-947a-408f-b0f7-5928493c29f3.jpg)

> Szczegółowe informacje na temat wywoływania debugowania w trybie JIT (just in time)
zamiast tego okna dialogowego znajdują się na końcu tego komunikatu.

************** Tekst wyjątku **************
System.ArgumentNullException: Wartość nie może być zerowa.
Nazwa parametru: uriString
   w System.Uri..ctor(String uriString)
   w MultiMiner.UX.ViewModels.ApplicationViewModel.InstallBackendMinerLocally(MinerDescriptor miner) w c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.UX\ViewModels\ApplicationViewModel.cs:wiersz 2219
   w MultiMiner.Win.Forms.MinerForm.ShowNotInstalledMinerWarning() w c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:wiersz 2580
   w MultiMiner.Win.Forms.MinerForm.ScanHardwareLocally() w c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:wiersz 2875
   w MultiMiner.Win.Forms.MinerForm.SetupApplication() w c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\MinerForm.cs:wiersz 2221
   w System.Windows.Forms.Form.OnLoad(EventArgs e)
   w System.Windows.Forms.Form.OnCreateControl()
   w System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   w System.Windows.Forms.Control.CreateControl()
   w System.Windows.Forms.Control.WmShowWindow(Message& m)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.Form.WmShowWindow(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Zestawy załadowane **************
mscorlib
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.Win.exe
----------------------------------------
MultiMiner.UX
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.UX.DLL
----------------------------------------
System.Drawing
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
MultiMiner.Engine
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.Engine.DLL
----------------------------------------
MultiMiner.Utility
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.Utility.DLL
----------------------------------------
System.Windows.Forms
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
MultiMiner.CoinApi
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.CoinApi.DLL
----------------------------------------
MultiMiner.Xgminer.Api
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.Xgminer.Api.DLL
----------------------------------------
MultiMiner.Xgminer
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.Xgminer.DLL
----------------------------------------
MultiMiner.MobileMiner
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.MobileMiner.DLL
----------------------------------------
MultiMiner.Discovery
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.Discovery.DLL
----------------------------------------
System.Xml
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Core
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Wersja zestawu: 1.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Wersja zestawu: 1.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Remoting
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.Remoting.DLL
----------------------------------------
Microsoft.GeneratedCode
    Wersja zestawu: 1.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.CoinWarz
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.CoinWarz.DLL
----------------------------------------
MultiMiner.WhatToMine
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.WhatToMine.DLL
----------------------------------------
Microsoft.GeneratedCode
    Wersja zestawu: 1.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Wersja zestawu: 6.0.0.0
    Wersja Win32: 6.0.8.18111
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/System.resources.dll
----------------------------------------
Microsoft.GeneratedCode
    Wersja zestawu: 1.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Services
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.Services.DLL
----------------------------------------
MultiMiner.Blockchain
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.Blockchain.DLL
----------------------------------------
MultiMiner.ExchangeApi
    Wersja zestawu: 4.3.1.382
    Wersja Win32: 4.3.1.382
    CodeBase: file:///C:/Users/user2/AppData/Local/MultiMiner/MultiMiner.ExchangeApi.DLL
----------------------------------------
Microsoft.GeneratedCode
    Wersja zestawu: 1.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    Wersja zestawu: 4.0.0.0
    Wersja Win32: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pl_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Debugowanie w trybie JIT **************
Aby włączyć debugowanie w trybie just in time (JIT), plik .config tej
aplikacji lub komputera (machine.config) musi mieć
wartość jitDebugging ustawioną w sekcji system.windows.forms.
Aplikacja musi być również skompilowana z włączonym
debugowaniem.

Na przykład:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Gdy debugowanie JIT jest włączone, wszystkie nieobsługiwane wyjątki
są wysyłane do debugera JIT zarejestrowanego na komputerze
i nie są obsługiwane w tym oknie dialogowym.

**************
I've clicked to continue an then the Multminer opens.
![3](https://user-images.githubusercontent.com/92303654/136781408-c137c0a4-bc5a-4f51-8f7f-0e41c5b91429.jpg)
View after clicking the notifiication.
![4](https://user-images.githubusercontent.com/92303654/136781576-ac6ce17d-ae1d-434b-b78a-3ba579a2d3e3.jpg)
Screen of my activated/deactivated Windows features.
![5](https://user-images.githubusercontent.com/92303654/136786600-16ca29b2-d9f8-4811-8982-c07d93df0d26.jpg)

If you need translation please don't hesitate to ask. I'd appreciate any answer, because i want to start the mining process ;-)

Regards,
Luke K

**Comment by 40P3** [comment]
Same here.
What .net sdk you want us to install though? Do we need additional .net to be installed other than win10's default?
![image](https://user-images.githubusercontent.com/20872247/142192222-ac76ddc9-2247-40f0-8150-6efa1588b9a4.png)

**Comment by 40P3** [comment]
Reverted back to 4.3.0 and at least if I copied the bfgminer into the folder it didn't cry that I need to install BFG miner.
However the .net error remains:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at MultiMiner.Win.Forms.WizardForm.DownloadChosenMiner() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\WizardForm.cs:line 171
   at MultiMiner.Win.Forms.WizardForm.nextButton_Click(Object sender, EventArgs e) in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\WizardForm.cs:line 127
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.Win.exe
----------------------------------------
MultiMiner.UX
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.UX.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
MultiMiner.Engine
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.Engine.DLL
----------------------------------------
MultiMiner.Utility
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.Utility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
MultiMiner.CoinApi
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.CoinApi.DLL
----------------------------------------
MultiMiner.Xgminer.Api
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.Xgminer.Api.DLL
----------------------------------------
MultiMiner.Xgminer
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.Xgminer.DLL
----------------------------------------
MultiMiner.MobileMiner
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.MobileMiner.DLL
----------------------------------------
MultiMiner.Discovery
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.Discovery.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.Remoting
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.Remoting.DLL
----------------------------------------
MultiMiner.CoinWarz
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.CoinWarz.DLL
----------------------------------------
MultiMiner.WhatToMine
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.WhatToMine.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
    CodeBase: file:///F:/Documents/Miner/MultiMiner/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MultiMiner.ExchangeApi
    Assembly Version: 4.3.0.381
    Win32 Version: 4.3.0.381
    CodeBase: file:///F:/Documents/Miner/MultiMiner/MultiMiner.ExchangeApi.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
