### ISSUE TITLE
Error "System.ArgumentNullException: Value cannot be null."

### ISSUE THREAD

**Issue by itsCliz** [nwoolls/MultiMiner#441]
i just install multiminer application and found some error like this:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at MultiMiner.Win.Forms.WizardForm.DownloadChosenMiner() in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\WizardForm.cs:line 171
   at MultiMiner.Win.Forms.WizardForm.nextButton_Click(Object sender, EventArgs e) in c:\Users\nwool\Documents\Visual Studio 2017\Projects\MultiMiner\MultiMiner.Win\Forms\WizardForm.cs:line 127
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MultiMiner.Win
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/User/AppData/Local/MultiMiner/MultiMiner.Win.exe
----------------------------------------
MultiMiner.UX
    Assembly Version: 4.3.1.382
    Win32 Version: 4.3.1.382
    CodeBase: file:///C:/Users/User/AppData/Local/MultiMiner/MultiMiner.UX.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
```

How to fix this??

**Comment by LDev-IX** [comment]
Same issue, I have .Net 6.0 installed.
I'll try to install an older version of .Net, and if it works I will post a link to download it right here.

**Comment by LDev-IX** [comment]
Nah, I installed .Net 5.0 and .Net framework 4.8, and it still doesn't work.
